// <auto-generated />
// Generated by chummer-android/scripts/materialize_android_character_settings_phone_capabilities.py.
#nullable enable
using System.Globalization;

namespace Chummer.Android.Native;

internal sealed record AndroidCharacterSettingCapability(
    string LegacyControl,
    string FieldId,
    string SectionId,
    string InputType,
    bool IsMultiline,
    string AndroidBehavior,
    string LabelResourceKey,
    string EnglishLabel);

internal static class AndroidCharacterSettingsPhoneCapabilities
{
    internal static IReadOnlyList<AndroidCharacterSettingCapability> Supported { get; } =
    [
        new("cboBuildMethod", "characterSettingsControl-cboBuildMethod", "build", "select", false, "selects the preferred build method for the phone creation wizard", "CharacterSettingBuildMethod", "Creation build method"),
        new("chkDontUseCyberlimbCalculation", "characterSettingsControl-chkDontUseCyberlimbCalculation", "ware", "checkbox", false, "changes cyberlimb participation in phone career attribute totals", "CharacterSettingDontUseCyberlimbCalculation", "Ignore cyberlimbs in augmented attribute totals"),
        new("cboLimbCount", "characterSettingsControl-cboLimbCount", "ware", "select", false, "changes which cyberlimb slots participate in phone career attribute totals", "CharacterSettingCyberlimbConfiguration", "Cyberlimb slots used for attribute totals"),
        new("nudKarmaNewActiveSkill", "characterSettingsControl-nudKarmaNewActiveSkill", "karma", "number", false, "sets the phone career cost for learning an active skill", "CharacterSettingKarmaNewActiveSkill", "Karma cost: new active skill"),
        new("nudKarmaImproveActiveSkill", "characterSettingsControl-nudKarmaImproveActiveSkill", "karma", "number", false, "sets the phone career cost multiplier for improving an active skill", "CharacterSettingKarmaImproveActiveSkill", "Karma multiplier: improve active skill"),
        new("nudKarmaNewSkillGroup", "characterSettingsControl-nudKarmaNewSkillGroup", "karma", "number", false, "sets the phone career cost for learning a skill group", "CharacterSettingKarmaNewSkillGroup", "Karma cost: new skill group"),
        new("nudKarmaImproveSkillGroup", "characterSettingsControl-nudKarmaImproveSkillGroup", "karma", "number", false, "sets the phone career cost multiplier for improving a skill group", "CharacterSettingKarmaImproveSkillGroup", "Karma multiplier: improve skill group"),
        new("chkCompensateSkillGroupKarmaDifference", "characterSettingsControl-chkCompensateSkillGroupKarmaDifference", "rules", "checkbox", false, "changes phone career active-skill cost when a linked group has a different rating", "CharacterSettingCompensateSkillGroupKarmaDifference", "Compensate skill-group Karma difference"),
        new("nudKarmaAttribute", "characterSettingsControl-nudKarmaAttribute", "karma", "number", false, "sets the phone career cost multiplier for improving an attribute", "CharacterSettingKarmaAttribute", "Karma multiplier: improve attribute"),
        new("chkAlternateMetatypeAttributeKarma", "characterSettingsControl-chkAlternateMetatypeAttributeKarma", "rules", "checkbox", false, "changes metatype-adjusted phone career attribute costs", "CharacterSettingAlternateMetatypeAttributeKarma", "Use alternate metatype attribute Karma"),
        new("chkUnclampAttributeMinimum", "characterSettingsControl-chkUnclampAttributeMinimum", "rules", "checkbox", false, "changes minimum values used by the phone career attribute projector", "CharacterSettingUnclampAttributeMinimum", "Allow attributes below the normal minimum"),
        new("chkMysAdeptSecondMAGAttribute", "characterSettingsControl-chkMysAdeptSecondMAGAttribute", "rules", "checkbox", false, "changes second-Magic handling in phone career attribute advancement", "CharacterSettingMysticAdeptSecondMagicAttribute", "Use a second Magic attribute for mystic adepts"),
        new("nudKarmaNewKnowledgeSkill", "characterSettingsControl-nudKarmaNewKnowledgeSkill", "karma", "number", false, "sets the phone career cost for learning a knowledge skill", "CharacterSettingKarmaNewKnowledgeSkill", "Karma cost: new knowledge skill"),
        new("nudKarmaImproveKnowledgeSkill", "characterSettingsControl-nudKarmaImproveKnowledgeSkill", "karma", "number", false, "sets the phone career cost multiplier for improving a knowledge skill", "CharacterSettingKarmaImproveKnowledgeSkill", "Karma multiplier: improve knowledge skill"),
        new("nudMaxSkillRating", "characterSettingsControl-nudMaxSkillRating", "limits", "number", false, "caps active-skill and skill-group ratings in phone career advancement", "CharacterSettingMaxSkillRating", "Maximum career active-skill rating"),
        new("nudMaxKnowledgeSkillRating", "characterSettingsControl-nudMaxKnowledgeSkillRating", "limits", "number", false, "caps knowledge-skill ratings in phone career advancement", "CharacterSettingMaxKnowledgeSkillRating", "Maximum career knowledge-skill rating"),
        new("chkUsePointsOnBrokenGroups", "characterSettingsControl-chkUsePointsOnBrokenGroups", "rules", "checkbox", false, "changes phone career active-skill, group, and specialization eligibility", "CharacterSettingUsePointsOnBrokenGroups", "Allow points on broken skill groups"),
    ];

    private static readonly IReadOnlyDictionary<string, AndroidCharacterSettingCapability> ByFieldId =
        Supported.ToDictionary(capability => capability.FieldId, StringComparer.Ordinal);

    internal static IReadOnlySet<string> SupportedSectionIds { get; } = Supported
        .Select(capability => capability.SectionId)
        .ToHashSet(StringComparer.Ordinal);

    internal static bool TryGet(string fieldId, out AndroidCharacterSettingCapability capability)
        => ByFieldId.TryGetValue(fieldId, out capability!);

    internal static string LocalizeLabel(AndroidCharacterSettingCapability capability, CultureInfo? culture)
        => PhoneStrings.Get(capability.LabelResourceKey, capability.EnglishLabel, culture);
}
