using Chummer.Contracts.Characters;

namespace Chummer.Android.Native;

internal static class CreationKarmaCopy
{
    public static string Magic => CreationAllocationStrings.Get("Karma.Magic", "Magic / Resonance");
    public static string Tradition => CreationAllocationStrings.Get("Karma.Tradition", "Tradition");
    public static string Stream => CreationAllocationStrings.Get("Karma.Stream", "Stream");
    public static string TraditionRequired => CreationAllocationStrings.Get("Karma.TraditionRequired", "Choose a tradition before saving this magic draft.");
    public static string StreamRequired => CreationAllocationStrings.Get("Karma.StreamRequired", "Choose a stream before saving this Resonance draft.");
    public static string Blocker(string code) => code switch
    {
        CharacterCreationMagicResonanceBlockers.TraditionRequired => TraditionRequired,
        CharacterCreationMagicResonanceBlockers.StreamRequired => StreamRequired,
        _ => code
    };
    public static string Powers => CreationAllocationStrings.Get("Karma.Powers", "Adept powers");
    public static string Spells => CreationAllocationStrings.Get("Karma.Spells", "Spells");
    public static string ComplexForms => CreationAllocationStrings.Get("Karma.ComplexForms", "Complex forms");
    public static string MagicHelp => CreationAllocationStrings.Get("Karma.MagicHelp", "Choose from your active sources. Core checks access, costs and limits. Karma pays for spells, complex forms and Mystic Adept power points; there are no free Priority spell slots. Only confirming the draft saves these choices.");
    public static string MagicTotals(int spells, int forms, int points, int total) => CreationAllocationStrings.Format("Karma.MagicTotals", "Spells: {0} Karma · forms: {1} · power points: {2} · total: {3}", spells, forms, points, total);
    public static string PowerBudget(decimal used, decimal total) => CreationAllocationStrings.Format("Karma.PowerBudget", "Power points: {0} / {1}", used, total);
    public static string PowerPointPurchase(int points, int karma) => CreationAllocationStrings.Format("Karma.PowerPointPurchase", "Purchased power points: {0} · {1} Karma", points, karma);
    public static string PowerLevel(decimal points, int levels) => CreationAllocationStrings.Format("Karma.PowerLevel", "{0} power points per level · selected levels: {1}", points, levels);
    public static string AddPowerPoint => CreationAllocationStrings.Get("Karma.AddPowerPoint", "Buy one power point");
    public static string RemovePowerPoint => CreationAllocationStrings.Get("Karma.RemovePowerPoint", "Remove one power point");
    public static string AddPowerLevel => CreationAllocationStrings.Get("Karma.AddPowerLevel", "Add one level");
    public static string MetatypeBonuses(int armor, int reach, int lifestylePercent) => CreationAllocationStrings.Format(
        "Karma.MetatypeBonuses", "Base metatype effects: armor +{0} · reach +{1} · lifestyle cost +{2}%", armor, reach, lifestylePercent);
    public static string ChooseStepFirst(string step) => CreationAllocationStrings.Format("Karma.ChooseStepFirst", "Choose {0} first.", step);
    public static string ReviewStepFirst(string step) => CreationAllocationStrings.Format("Karma.ReviewStepFirst", "Open {0} and review your choices first.", step);
    public static string ReviewOptionalStepFirst(string step) => CreationAllocationStrings.Format("Karma.ReviewOptionalStepFirst", "Open {0} first, even if you keep the selection empty.", step);
    public static string ApplyResourcesFirst(string step) => CreationAllocationStrings.Format("Karma.ApplyResourcesFirst", "Open {0} and apply an amount to the draft (0 is allowed).", step);
    public static string UnavailableInCurrentRules(string step) => CreationAllocationStrings.Format("Karma.UnavailableInCurrentRules", "{0} is unavailable with the current rule settings.", step);
    public static string Lifestyles => CreationAllocationStrings.Get("Karma.Lifestyles", "Lifestyles");
    public static string LifestyleHelp => CreationAllocationStrings.Get("Karma.LifestyleHelp", "Configure standard lifestyles in the pending draft, then explicitly choose one purchased lifestyle for starting cash. Equipment and lifestyles share the same funding; the later cash roll cannot pay for purchases. Advanced aspects and optional lifestyle qualities are not offered here yet. Only draft confirmation saves.");
    public static string UseStartingLifestyle => CreationAllocationStrings.Get("Karma.UseStartingLifestyle", "Use for starting cash");
    public static string StartingLifestyleSelected => CreationAllocationStrings.Get("Karma.StartingLifestyleSelected", "Selected for starting cash");
    public static string LifestyleIncrements => CreationAllocationStrings.Get("Karma.LifestyleIncrements", "Number of source periods");
    public static string LifestylePercentage => CreationAllocationStrings.Get("Karma.LifestylePercentage", "Cost percentage");
    public static string LifestyleRoommates => CreationAllocationStrings.Get("Karma.LifestyleRoommates", "Roommates");
    public static string LifestyleSplit => CreationAllocationStrings.Get("Karma.LifestyleSplit", "Split cost with roommates");
    public static string LifestyleTrustFund => CreationAllocationStrings.Get("Karma.LifestyleTrustFund", "Use Trust Fund (Core must confirm eligibility)");
    public static string LifestyleCity => CreationAllocationStrings.Get("Karma.LifestyleCity", "City");
    public static string LifestyleDistrict => CreationAllocationStrings.Get("Karma.LifestyleDistrict", "District");
    public static string LifestyleBorough => CreationAllocationStrings.Get("Karma.LifestyleBorough", "Borough");
    public static string LifestyleSource(string name, decimal cost, string period) => CreationAllocationStrings.Format("Karma.LifestyleSource", "{0} · base {1:N2} ¥ per {2}", name, cost, period);
    public static string LifestyleLine(string name, string basis, decimal total) => CreationAllocationStrings.Format("Karma.LifestyleLine", "{0} · {1} · total {2:N2} ¥", name, basis, total);
    public static string LifestyleTotals(decimal total, decimal gear, decimal lifestyles, decimal remaining, decimal overspend) => CreationAllocationStrings.Format("Karma.LifestyleTotals", "Funding: {0:N2} ¥ · equipment: {1:N2} ¥ · lifestyles: {2:N2} ¥ · remaining: {3:N2} ¥ · over budget: {4:N2} ¥", total, gear, lifestyles, remaining, overspend);
    public static string Contacts => CreationAllocationStrings.Get("Karma.Contacts", "Contacts");
    public static string ContactHelp => CreationAllocationStrings.Get("Karma.ContactHelp", "Add contacts to the pending draft. Core prices contact points, Karma and quality limits. Groups need Loyalty 1. Free-point overspend costs Karma. Nothing is saved until you confirm the draft.");
    public static string AddContact => CreationAllocationStrings.Get("Karma.AddContact", "Add contact");
    public static string UnnamedContact => CreationAllocationStrings.Get("Karma.UnnamedContact", "Unnamed contact");
    public static string ContactName => CreationAllocationStrings.Get("Karma.ContactName", "Name");
    public static string ContactRole => CreationAllocationStrings.Get("Karma.ContactRole", "Role");
    public static string ContactLocation => CreationAllocationStrings.Get("Karma.ContactLocation", "Location");
    public static string ContactNotes => CreationAllocationStrings.Get("Karma.ContactNotes", "Notes");
    public static string Connection => CreationAllocationStrings.Get("Karma.Connection", "Connection");
    public static string Loyalty => CreationAllocationStrings.Get("Karma.Loyalty", "Loyalty");
    public static string GroupContact => CreationAllocationStrings.Get("Karma.GroupContact", "Group contact (set Loyalty to 1)");
    public static string FamilyContact => CreationAllocationStrings.Get("Karma.FamilyContact", "Family");
    public static string BlackmailContact => CreationAllocationStrings.Get("Karma.BlackmailContact", "Blackmail");
    public static string ContactLine(string name, int connection, int loyalty, int points) => CreationAllocationStrings.Format("Karma.ContactLine", "{0} · Connection {1} · Loyalty {2} · {3} contact points", name, connection, loyalty, points);
    public static string ContactTotals(int used, int total, int highUsed, int highTotal, int karma) => CreationAllocationStrings.Format("Karma.ContactTotals", "Contact points: {0}/{1} · High Places: {2}/{3} · additional Karma: {4}", used, total, highUsed, highTotal, karma);
    public static string GroupContactCost(int karma, int limitUsed) => CreationAllocationStrings.Format("Karma.GroupContactCost", "Group contacts: {0} Karma before excess costs · positive quality limit usage including groups: {1}", karma, limitUsed);
    public static string Finish => CreationAllocationStrings.Get("Karma.Finish", "Finish Karma creation");
    public static string CompletionHelp => CreationAllocationStrings.Get("Karma.CompletionHelp", "Review all changes before entering Career mode. Amounts above the carryover limits are lost. Starting cash cannot fund creation purchases. Awakened builds need a saved, valid Magic / Resonance selection.");
    public static string DiceTotal => CreationAllocationStrings.Get("Karma.DiceTotal", "Enter your dice total (no automatic roll)");
    public static string PreviewCompletion => CreationAllocationStrings.Get("Karma.PreviewCompletion", "Review Career transition");
    public static string ConfirmCompletion => CreationAllocationStrings.Get("Karma.ConfirmCompletion", "Confirm and enter Career");
    public static string CareerReady => CreationAllocationStrings.Get("Karma.CareerReady", "Creation saved. Career mode was reopened from the saved runner.");
    public static string CareerReopen => CreationAllocationStrings.Get("Karma.CareerReopen", "Creation saved. Reopen the runner before making further changes.");
    public static string OpenCareer => CreationAllocationStrings.Get("Karma.OpenCareer", "Open Career runner");
    public static string StartingCash(string name, int dice, decimal multiplier) => CreationAllocationStrings.Format("Karma.StartingCash", "{0}: roll {1}d6 · multiplier {2:N2} ¥", name, dice, multiplier);
    public static string CompletionTotals(decimal karma, decimal starting, decimal nuyen) => CreationAllocationStrings.Format("Karma.CompletionTotals", "Career Karma: {0} · creation funding: {1:N2} ¥ · Career nuyen: {2:N2} ¥", karma, starting, nuyen);
    public static string DeltaCost(decimal karma, decimal nuyen) => CreationAllocationStrings.Format("Karma.DeltaCost", "Cost: {0} Karma · {1:N2} ¥", karma, nuyen);
    public static string Title => CreationAllocationStrings.Get("Karma.Title", "Karma foundation");
    public static string Loading => CreationAllocationStrings.Get("Karma.Loading", "Checking rules and saved choices… Your draft is kept while this page loads.");
    public static string Metatype => CreationAllocationStrings.Get("Karma.Metatype", "Metatype");
    public static string Talent => CreationAllocationStrings.Get("Karma.Talent", "Talent");
    public static string Attributes => CreationAllocationStrings.Get("Karma.Attributes", "Attributes");
    public static string Qualities => CreationAllocationStrings.Get("Karma.Qualities", "Qualities");
    public static string QualityHelp => CreationAllocationStrings.Get("Karma.QualityHelp", "Choose qualities from your active sources. Source costs are shown per rating; Core applies profile multipliers and limits to the totals. Choices with unresolved effects or requirements are disabled. Only the final review saves the draft.");
    public static string QualityUnavailable => CreationAllocationStrings.Get("Karma.QualityUnavailable", "Unavailable in this draft");
    public static string Selected => CreationAllocationStrings.Get("Karma.Selected", "Selected");
    public static string QualitySourceCost(string name, int rating, int cost) => CreationAllocationStrings.Format("Karma.QualitySourceCost", "{0} · rating {1} · source cost {2} Karma", name, rating, cost);
    public static string QualityTotals(int positive, int negative, int net) => CreationAllocationStrings.Format("Karma.QualityTotals", "Qualities: cost {0} · credit {1} · net {2} Karma", positive, negative, net);
    public static string Skills => CreationAllocationStrings.Get("Karma.Skills", "Skills");
    public static string Groups => CreationAllocationStrings.Get("Karma.Groups", "Skill groups");
    public static string Resources => CreationAllocationStrings.Get("Karma.Resources", "Resources");
    public static string Gear => CreationAllocationStrings.Get("Karma.Gear", "Equipment");
    public static string GearHelp => CreationAllocationStrings.Get("Karma.GearHelp", "Choose equipment from active sources. Quantities are units; adding an item selects one source package. Core checks costs and availability. Review and confirm to save the draft.");
    public static string GearUnavailable => CreationAllocationStrings.Get("Karma.GearUnavailable", "Unavailable in this equipment draft");
    public static string GearLine(string name, int quantity, decimal cost) => CreationAllocationStrings.Format("Karma.GearLine", "{0} · {1} units · {2:N2} ¥", name, quantity, cost);
    public static string GearTotals(decimal total, decimal spent, decimal remaining, decimal overspend) => CreationAllocationStrings.Format("Karma.GearTotals", "Equipment: {0:N2} ¥ available · {1:N2} ¥ spent · {2:N2} ¥ remaining · {3:N2} ¥ over budget", total, spent, remaining, overspend);
    public static string ResourceInvestment => CreationAllocationStrings.Get("Karma.ResourceInvestment", "Karma to invest");
    public static string ResourceHelp => CreationAllocationStrings.Get("Karma.ResourceHelp", "Preview profile-funded nuyen for the equipment draft. Quality-based nuyen modifiers and final starting cash are not included yet. Use this amount in the draft, then review to save.");
    public static string InvalidNumber => CreationAllocationStrings.Get("Karma.InvalidNumber", "Enter a non-negative number using your language's decimal separator, without thousands separators.");
    public static string ResourceLimit(decimal maximum) => CreationAllocationStrings.Format("Karma.ResourceLimit", "Profile limit: {0} Karma", maximum);
    public static string ResourceFunding(decimal karma, decimal nuyen) => CreationAllocationStrings.Format("Karma.ResourceFunding", "Resources: {0} Karma → {1} ¥ (profile funding, before equipment)",
        karma.ToString("G29", System.Globalization.CultureInfo.CurrentCulture),
        nuyen.ToString("N2", System.Globalization.CultureInfo.CurrentCulture));
    public static string Review => CreationAllocationStrings.Get("Karma.Review", "Review draft");
    public static string Scope => CreationAllocationStrings.Get("Karma.Scope", "Experimental Karma creation with source-validated magic purchases. Save the draft first, then separately review and confirm Career entry. Unsupported source options remain disabled; this is not all-method parity.");
    public static string Stale => CreationAllocationStrings.Get("Karma.Stale", "This draft is no longer ready. Return to the runner and reopen it; no selection is applied automatically.");
    public static string Saved => CreationAllocationStrings.Get("Karma.Saved", "Pending Karma draft saved. The runner has not been finalized.");
    public static string Choose => CreationAllocationStrings.Get("Karma.Choose", "Choose explicitly");
    public static string Pending => CreationAllocationStrings.Get("Karma.Pending", "Selection changed — refresh the preview for current totals and costs.");
    public static string LevelHelp => CreationAllocationStrings.Get("Karma.LevelHelp", "Adjust purchased levels. Core recalculates final ratings, limits and costs when you refresh the preview.");
    public static string Preview => CreationAllocationStrings.Get("Karma.Preview", "Refresh preview");
    public static string Active => CreationAllocationStrings.Get("Karma.Active", "Active skills");
    public static string Knowledge => CreationAllocationStrings.Get("Karma.Knowledge", "Knowledge points");
    public static string KnowledgeSkills => CreationAllocationStrings.Get("Karma.KnowledgeSkills", "Knowledge skills");
    public static string Search => CreationAllocationStrings.Get("Karma.Search", "Search catalog");
    public static string Previous => CreationAllocationStrings.Get("Karma.Previous", "Previous page");
    public static string Next => CreationAllocationStrings.Get("Karma.Next", "Next page");
    public static string SkillHelp => CreationAllocationStrings.Get("Karma.SkillHelp", "Choose the payment and source option, then use this selection in the draft. Only the final review saves it.");
    public static string KarmaLevels => CreationAllocationStrings.Get("Karma.KarmaLevels", "Karma-paid levels");
    public static string KnowledgeLevels => CreationAllocationStrings.Get("Karma.KnowledgeLevels", "Knowledge-point levels");
    public static string NativeLanguage => CreationAllocationStrings.Get("Karma.NativeLanguage", "Native language");
    public static string Specialization => CreationAllocationStrings.Get("Karma.Specialization", "Specialization / exotic identity");
    public static string None => CreationAllocationStrings.Get("Karma.None", "None");
    public static string Payment => CreationAllocationStrings.Get("Karma.Payment", "Specialization payment");
    public static string Karma => CreationAllocationStrings.Get("Karma.Karma", "Karma");
    public static string UseSelection => CreationAllocationStrings.Get("Karma.UseSelection", "Use selection in draft");
    public static string Remove => CreationAllocationStrings.Get("Karma.Remove", "Remove from draft");
    public static string Confirm => CreationAllocationStrings.Get("Karma.Confirm", "Confirm and save pending draft");
    public static string Binding(long revision, long saved) => CreationAllocationStrings.Format("Karma.Binding", "Revision {0} · saved {1}", revision, saved);
    public static string Budget(decimal spent, decimal total, decimal remaining) => CreationAllocationStrings.Format("Karma.Budget", "Karma: {0} / {1} · remaining {2}", spent, total, remaining);
    public static string Cost(string name, decimal cost) => CreationAllocationStrings.Format("Karma.Cost", "{0} · {1} Karma", name, cost);
    public static string Levels(string name, int levels) => CreationAllocationStrings.Format("Karma.Levels", "{0}: {1}", name, levels);
    public static string KnowledgeBudget(decimal used, decimal total) => CreationAllocationStrings.Format("Karma.KnowledgeBudget", "Knowledge points: {0} / {1}", used, total);
    public static string ValueCost(string name, object rating, decimal cost) => CreationAllocationStrings.Format("Karma.ValueCost", "{0}: {1} · {2} Karma", name, rating, cost);
}
