#!/usr/bin/env python3
"""Display-only subset of the pinned Core skill names; emits an apply_patch patch.

No ratings, rules, IDs or runtime source files are rewritten. Read names by exact
source ID and English name, never by a translated label. --check detects stale
generated resources after a Core content repin. No network or runtime XML load.
"""
import argparse
import hashlib
from pathlib import Path
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape, quoteattr


# The pinned German catalog contains legacy renamed rows under some SR5 IDs
# (e.g. Navigation -> Query -> Abfrage). Do not apply those different meanings.
# These short, independently written SR5 display labels deliberately replace
# only the named English label, not its identity or any rule.
GERMAN_NAMES = {
    "Assensing": "Askennen", "Automotive Mechanic": "Bodenfahrzeugmechanik",
    "Blades": "Klingenwaffen", "Clubs": "Schlagwaffen", "Computer": "Computer",
    "Cybercombat": "Cyberkampf", "Etiquette": "Etikette", "Gymnastics": "Akrobatik",
    "Hardware": "Hardware", "Leadership": "Führung", "Navigation": "Navigation",
    "Negotiation": "Verhandlung", "Palming": "Fingerfertigkeit",
    "Pilot Ground Craft": "Bodenfahrzeuge", "Pistols": "Pistolen",
    "Running": "Laufen", "Swimming": "Schwimmen", "Creole": "Kreolisch",
    "Tamazight": "Tamazight",
}


def token(value):
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def resources(core):
    raw = {name: (core / name).read_bytes()
           for name in ("data/skills.xml", "lang/de-de_data.xml")}
    source = ET.fromstring(raw["data/skills.xml"])
    german = ET.fromstring(raw["lang/de-de_data.xml"]).find("chummer[@file='skills.xml']")
    if german is None:
        raise ValueError("No German skills catalog")
    english, translated = {}, {}
    for section, kind in (("skills", "active"), ("knowledgeskills", "knowledge")):
        localized = {row.findtext("id"): row for row in german.find(section)}
        for row in source.find(section):
            identity, name = row.findtext("id"), row.findtext("name")
            prefix = f"Skill.{kind}.{identity}"
            key = prefix + ".Name"
            if not identity or not name or key in english:
                raise ValueError("Missing or duplicate source identity/name")
            english[key] = name
            other = localized.get(identity)
            exact = other is not None and other.findtext("name") == name
            label = GERMAN_NAMES.get(name) or (other.findtext("translate") if exact else None)
            if label:
                translated[key] = label
            specs = {item.text: item.get("translate") for item in other.findall("specs/spec")} if exact else {}
            for spec in row.findall("specs/spec"):
                if not spec.text:
                    continue
                key = prefix + ".Spec." + token(spec.text)
                english[key] = spec.text
                if specs.get(spec.text):
                    translated[key] = specs[spec.text]
    for section, item, kind in (("skillgroups", "name", "Group"), ("categories", "category", "Category")):
        labels = {row.text: row.get("translate") for row in german.findall(f"{section}/{item}")}
        for row in source.findall(f"{section}/{item}"):
            key = kind + "." + token(row.text)
            english[key] = row.text
            if labels.get(row.text):
                translated[key] = labels[row.text]
    stamps = " ".join(f"{name} sha256={hashlib.sha256(data).hexdigest()}" for name, data in raw.items())
    return {suffix: render(values, stamps) for suffix, values in (("", english), (".de", translated))}


def render(values, stamps):
    lines = ['<?xml version="1.0" encoding="utf-8"?>', '<root>',
             '  <!-- Generated by scripts/materialize_skill_catalog_strings.py; display-only. -->',
             '  <!-- ' + stamps + ' -->']
    for name, value in (("resmimetype", "text/microsoft-resx"), ("version", "2.0"),
                        ("reader", "System.Resources.ResXResourceReader, System.Windows.Forms"),
                        ("writer", "System.Resources.ResXResourceWriter, System.Windows.Forms")):
        lines.append(f'  <resheader name="{name}"><value>{value}</value></resheader>')
    for key, value in sorted(values.items()):
        lines.append(f'  <data name={quoteattr(key)} xml:space="preserve"><value>{escape(value)}</value></data>')
    return "\n".join(lines + ["</root>", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--core-content-root", type=Path, required=True, help="Directory containing data/ and lang/")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    outputs = resources(args.core_content_root)
    patches = []
    for suffix, text in outputs.items():
        path = Path(f"src/Chummer.Android/Resources/Localization/SkillCatalogStrings{suffix}.resx")
        target = repo / path
        old = target.read_text() if target.exists() else None
        if old == text:
            continue
        if args.check:
            raise SystemExit(f"Stale or missing display resource: {path}")
        if old is not None:
            patches.append(f"*** Update File: {path}\n@@\n" + "\n".join("-" + line for line in old.splitlines())
                           + "\n" + "\n".join("+" + line for line in text.splitlines()))
        else:
            patches.append(f"*** Add File: {path}\n" + "\n".join("+" + line for line in text.splitlines()))
    if args.check:
        print("PASS skill display resources match exact Core inputs and reviewed German name corrections")
    elif patches:
        print("*** Begin Patch\n" + "\n".join(patches) + "\n*** End Patch")


if __name__ == "__main__":
    main()
